---
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    capabilities:
      - SYS_ADMIN
    command: /bin/bash -c "apt-get update && apt-get install -y systemd && exec /lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false
      timeout: 30
  inventory:
    group_vars:
      all:
        nginx_package: nginx
        php_packages:
          - php-fpm
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
        mysql_package: mysql-server
        web_user: www-data
        php_fpm_service: php8.1-fpm
        wordpress_version: "6.4"
verifier:
  name: ansible
